version: '3.7'

services:
  lineageos:
    container_name: lineageos
    build: ./docker-lineage-cicd
    env_file:
      ./lineageos.env
    volumes:
      - /home/oynqr/lineageos/src:/srv/src
      - /home/oynqr/lineageos/zips:/srv/zips
      - /home/oynqr/lineageos/logs:/srv/logs
      - /home/oynqr/lineageos/ccache:/srv/ccache
      - /home/oynqr/lineageos/certs:/srv/keys
      - ./manifests:/srv/local_manifests
    network_mode: "host"
